version: "3"

services:
  webapp:
    image: ppppk/tttm:1.0
    ports:
      - "8081:8080"
    volumes:
      - "/data"
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:6.2.5
    restart: always
    privileged: true
    ports:
      - "6389:6379"
    volumes:
      - /home/pan/build/tttm/redis/redis.conf:/etc/redis/redis.conf
      - /home/pan/build/tttm/redis/data:/data
      - /home/pan/build/tttm/redis/redis.log:/redis/redis.log
    command: redis-server /etc/redis/redis.conf

  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3307:3306"
    volumes:
      - "/home/pan/build/tttm/mysql/data:/var/lib/mysql"
      - "/home/pan/build/tttm/mysql/my.cnf:/etc/my.cnf"

